import "./globals.css";
import type { Metadata } from "next";
import { Scada } from "next/font/google";
import Head from "next/head";
// import { Providers } from "./providers";

const scada = Scada({
  weight: "400",
  subsets: ["cyrillic-ext", "latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
        />
      </Head>
      <body className={scada.className} style={{ padding: 0, margin: 0 }}>
        {children}
      </body>
    </html>
  );
}
