import "./globals.css";
import type { Metadata } from "next";
import { Scada } from "next/font/google";
// import { Providers } from "./providers";

const scada = Scada({
  weight: "400",
  subsets: ["cyrillic-ext", "latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1, maximum-scale=1" />
      </head>
      <body className={scada.className} style={{ padding: 0, margin: 0 }}>
        {children}
      </body>
    </html>
  );
}
